services:
  nx5-carmod:
    build: .
    image: nx5-carmod:latest
    privileged: true
    volumes:
      - ./output:/opt/output
      - ./configs:/opt/configs
      - ./scripts:/opt/scripts
      - ./build.sh:/opt/build.sh
     # - ./test:/opt/build
    command: ["bash", "/build.sh"]
