services:
  nx5-carmod:
    build: Docker/nx5-carmod
    image: nx5-carmod:latest
    privileged: true
    volumes:
      - ./output:/opt/output
      - ./configs:/opt/configs
      #- ./test:/opt/build/
    command: ["bash", "/build.sh"]